import json
import os
from datetime import datetime

def generate_report(results_path="output/extraction_results.json", output_dir="output"):
    with open(results_path) as f:
        results = json.load(f)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    passed, needs_review, not_found = 0, 0, 0
    for section in results.values():
        for a in section["answers"]:
            s = a["status"]
            if s == "passed": passed += 1
            elif s == "needs_review": needs_review += 1
            else: not_found += 1

    total = passed + needs_review + not_found
    score = round((passed / total) * 100) if total > 0 else 0
    if score >= 80: overall = "SATISFACTORY"
    elif score >= 50: overall = "NEEDS IMPROVEMENT"
    else: overall = "UNSATISFACTORY"

    R = []
    R.append("# Model Validation Working Paper")
    R.append(f"**Generated:** {now}")
    R.append("**Document:** Basel Committee on Banking Supervision - Model Risk Principles")
    R.append("")
    R.append("---")
    R.append("## Executive Summary")
    R.append("")
    R.append("| Metric | Value |")
    R.append("|---|---|")
    R.append(f"| Overall status | **{overall}** |")
    R.append(f"| Compliance score | {score}% ({passed}/{total} passed) |")
    R.append(f"| Passed | {passed} |")
    R.append(f"| Needs review | {needs_review} |")
    R.append(f"| Not found | {not_found} |")
    R.append("")
    R.append("---")

    icons = {"passed": "PASS", "needs_review": "REVIEW", "not_found": "FAIL"}

    for section in results.values():
        R.append(f"## {section['sheet']}")
        sec_p = sum(1 for a in section["answers"] if a["status"] == "passed")
        R.append(f"**Section score: {sec_p}/{len(section['answers'])}**")
        R.append("")
        for a in section["answers"]:
            icon = icons.get(a["status"], "?")
            R.append(f"### [{icon}] {a['id']} - {a['question']}")
            R.append(f"**Status:** {a['status'].replace('_', ' ').title()}")
            R.append(f"**Answer:** {a.get('answer', 'No answer recorded')}")
            eq = a.get("evidence_quote")
            if eq:
                R.append(f"**Evidence:** {eq}")
            pr = a.get("page_reference")
            if pr:
                R.append(f"**Page:** {pr}")
            nt = a.get("notes")
            if nt:
                R.append(f"**Notes:** {nt}")
            R.append("")
            R.append("---")
            R.append("")

    R.append("## Source Traceability")
    R.append("| ID | Page | Status |")
    R.append("|---|---|---|")
    for section in results.values():
        for a in section["answers"]:
            page = a.get("page_reference") or "N/A"
            R.append(f"| {a['id']} | {page} | {a['status']} |")
    R.append("")
    R.append("*Report generated by Model Validation Agent*")

    os.makedirs(output_dir, exist_ok=True)
    path = f"{output_dir}/validation_report.md"
    with open(path, "w") as f:
        f.write("\n".join(R))
    print(f"Report saved to {path}")
    return "\n".join(R)

if __name__ == "__main__":
    generate_report()
